(ns om-async.logger
  ;; TODO find a logger for server (clj) and client (cljs)
  ;; (:require [taoensso.timbre :as logger])
  )

(defn info [msg]
  (println msg))

;;;;;;;;;;;; This file autogenerated from src/cljx/om_async/logger.cljx
